//! The Noisemaker effect catalog: every effect definition and WGSL program of the
//! reference engine, embedded as static data.
//!
//! The catalog is generated by `tools/convert-effects.mjs` from a pinned checkout of
//! the reference engine. Definitions are the reference `definition.js` instances
//! serialized with `JSON.stringify` semantics; WGSL programs are byte-identical
//! copies of the reference shaders (`parity/check_effects.mjs` gates both).
//! The shared files beside them ([`share_file`]: built-in meshes, palettes,
//! effect strings, the demo's text font and its default media image,
//! [`test_card_png`]) are byte copies of the reference's.

/// One effect of the catalog.
#[derive(Debug, Clone, Copy)]
pub struct EffectSource {
    /// Namespace directory (`synth`, `filter`, ...).
    pub namespace: &'static str,
    /// Effect directory name (the `<namespace>/<name>` effect id).
    pub name: &'static str,
    /// The definition serialized as JSON.
    pub definition_json: &'static str,
    /// `(program, WGSL source)` pairs in program-name order.
    pub wgsl: &'static [(&'static str, &'static str)],
}

impl EffectSource {
    /// `<namespace>/<name>`.
    pub fn id(&self) -> String {
        format!("{}/{}", self.namespace, self.name)
    }

    /// The WGSL source of `program`, if the effect ships one.
    pub fn wgsl_program(&self, program: &str) -> Option<&'static str> {
        self.wgsl
            .iter()
            .find(|(p, _)| *p == program)
            .map(|(_, s)| *s)
    }
}

include!(concat!(env!("OUT_DIR"), "/catalog.rs"));

/// Look up an effect by namespace and effect directory name.
pub fn effect(namespace: &str, name: &str) -> Option<&'static EffectSource> {
    EFFECTS
        .iter()
        .find(|e| e.namespace == namespace && e.name == name)
}

/// A shared asset (built-in meshes) by its catalog path, e.g. `share/meshes/cube.obj`.
pub fn share_file(path: &str) -> Option<&'static [u8]> {
    SHARE_FILES
        .iter()
        .find(|(p, _)| *p == path)
        .map(|(_, b)| *b)
}

/// The catalog path of [`test_card_png`].
pub const TEST_CARD_PATH: &str = "share/img/testcard.png";

/// The reference demo's default media image (`demo/shaders/img/testcard.png`,
/// which `parity/check_effects.mjs` requires this copy to equal byte for
/// byte): the image the demo loads into every `synth/media` step until the
/// user picks another. PNG bytes, 768x576, 8-bit RGB.
///
/// Philips PM5544 test card, by Ebnz, modified by Tucvbif (Wikimedia Commons,
/// File:Philips_PM5544.svg), CC BY 2.5; rasterized to 768×576 for the
/// Noisemaker demo.
pub fn test_card_png() -> &'static [u8] {
    share_file(TEST_CARD_PATH).expect("the catalog ships the test card")
}

#[cfg(test)]
mod tests {
    #[test]
    fn catalog_is_complete() {
        assert_eq!(super::EFFECTS.len(), 210);
        let programs: usize = super::EFFECTS.iter().map(|e| e.wgsl.len()).sum();
        assert_eq!(programs, 308);
        assert!(
            super::effect("synth", "noise")
                .unwrap()
                .wgsl_program("noise")
                .is_some()
        );
        assert!(super::share_file("share/meshes/cube.obj").is_some());
        assert!(super::test_card_png().starts_with(b"\x89PNG\r\n\x1a\n"));
    }
}
